### PR TITLE
chore: Update dependencies, and migrate code to 2021 edition

### PR DESCRIPTION
**Pull request by Uzaaft**
The title pretty much says it all.
Just some maintenance for this crate.

### CODE REVIEW

**Comment by danielhstahl** [comment]
Looks like its still 2018?

**Comment by Uzaaft** [comment]
Ops, had to revert it for a moment. Give me 2s and I'll fix that

**Comment by Uzaaft** [comment]
My bad. Should be 2021 now

**Comment by Uzaaft** [comment]
2 tests seems to fail due to some floating point stuff. Screen below.
Perhaps I could go ahead and reduce the number of decimals we use in the test if it's alright with you danielhstahl

image

image


List over tests:
image

**Comment by danielhstahl** [comment]
Test seem to be passing in GHA?

**Comment by Uzaaft** [comment]
peculiar....very peculiar

**Pull request merged**
