### PR TITLE
added vanna, vomma, charm

### PR DESCRIPTION
**Pull request by danielhstahl**
@brandonros Is this what you are looking for?

### CODE REVIEW

**Comment by brandonros** [comment]
highly highly highly appreciate it. Cannot thank you enough. Thank you for the quick turnaround time. If it’s OK with you I’ll make a tracking issue for the other. Not so popular second order and third order greeks and if you feel like having the most complete open source library, for this, by all means, feel free to implement them. Otherwise, this one is looking really good because if you Google about what’s out there, not only in rust, but also in python, not a lot of libraries, seem to have them all in one place. Thanks again, been a pleasure working with you so far.

**Comment by danielhstahl** [comment]
> highly highly highly appreciate it. Cannot thank you enough. Thank you for the quick turnaround time. If it’s OK with you I’ll make a tracking issue for the other. Not so popular second order and third order greeks and if you feel like having the most complete open source library, for this, by all means, feel free to implement them. Otherwise, this one is looking really good because if you Google about what’s out there, not only in rust, but also in python, not a lot of libraries, seem to have them all in one place. Thanks again, been a pleasure working with you so far.

Sure thing, please make an issue and I'll work towards it.

**Comment by brandonros** [comment]
@danielhstahl can you bump to 0.11.0 please when you have a moment and release for cargo?

**Comment by danielhstahl** [comment]
> @danielhstahl can you bump to 0.11.0 please when you have a moment and release for cargo?

0.10.0 should have the update: https://crates.io/crates/black_scholes/versions

**Pull request merged**
